CREATE TABLE IF NOT EXISTS groups
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(100),
    surname   varchar(100),
    age       int CHECK ( age > 0 ),
    phone     varchar(20) UNIQUE,
    login     varchar(100) NOT NULL,
    password  varchar(100) NOT NULL,
    role      varchar(20)  NOT NULL,
    user_type varchar(20)  NOT NULL
);

CREATE TABLE IF NOT EXISTS student_group
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  int UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    group_id int REFERENCES groups (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audience
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number int CHECK ( room_number > 0 )
);

CREATE TABLE IF NOT EXISTS course
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lecture
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    int REFERENCES course (id) ON DELETE SET NULL,
    teacher_id   int REFERENCES users (id) ON DELETE SET NULL,
    lecture_date date,
    group_id     int REFERENCES groups (id) ON DELETE SET NULL,
    pair_number  int CHECK ( pair_number > 0 ),
    audience_id  int REFERENCES audience (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS teacher_course
(
    user_id   int REFERENCES users (id) ON DELETE CASCADE,
    course_id int REFERENCES course (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, course_id)
);