ALTER TABLE teacher_course
    DROP CONSTRAINT IF EXISTS teacher_course_pkey;
ALTER TABLE teacher_course
    ADD COLUMN IF NOT EXISTS id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE teacher_course
    ADD CONSTRAINT user_course_constraint UNIQUE (user_id, course_id);