CREATE TABLE "lecture"
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_name varchar(100) NOT NULL,
    teacher_id   int          REFERENCES "user" (id) ON DELETE SET NULL,
    lecture_date date,
    group_id     int          REFERENCES "group" (id) ON DELETE SET NULL,
    pair_number  int CHECK ( pair_number > 0 ),
    lecture_day  varchar(20),
    audience_id  int          REFERENCES "audience" (id) ON DELETE SET NULL
);