CREATE TABLE "group"
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "user"
(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(100) NOT NULL,
    surname        varchar(100) NOT NULL,
    age            int CHECK ( age > 0 ),
    phone          varchar(20) UNIQUE,
    login          varchar(100),
    password       varchar(100),
    role           varchar(20),
    user_type      varchar(20),
    specialization varchar(20),
    course         int CHECK ( course > 0 ),
    faculty        varchar(50),
    group_id       int          REFERENCES "group" (id) ON DELETE SET NULL
);

CREATE TABLE "audience"
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number int CHECK ( room_number > 0 )
);

CREATE TABLE "lecture"
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_name varchar(100) NOT NULL,
    teacher_id   int          REFERENCES "user" (id) ON DELETE SET NULL,
    lecture_date date,
    group_id     int          REFERENCES "group" (id) ON DELETE SET NULL,
    pair_number  int CHECK ( pair_number > 0 ),
    lecture_day  varchar(20),
    audience_id  int          REFERENCES "audience" (id) ON DELETE SET NULL
);